services:
  feirinhas-ufrn:
    container_name: feirinhas-ufrn
    hostname: feirinhas-ufrn
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8083:8083"
  # POSTGRES
  postgres:
    image: postgres:16
    container_name: postgres-feirinhas-ufrn
    hostname: postgres
    environment:
      - POSTGRES_DB=feirinhas_ufrn
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_feirinhas_ufrn:/var/lib/postgresql/data 
    ports:
      - "5432:5432"
  # PGADMIN
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  themes: ~
  postgres_feirinhas_ufrn: ~
